# Generated by Django 3.2.5 on 2021-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='other_name',
            new_name='poste',
        ),
        migrations.AddField(
            model_name='staff',
            name='Subject',
            field=models.CharField(choices=[('FR', 'FR'), ('MATH', 'MATH')], default='MATH', max_length=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='type_post',
            field=models.CharField(choices=[('Enseignant', 'Enseignant'), ('Support', 'Support')], default='Enseignant', max_length=10),
        ),
    ]
