# Generated by Django 3.2.5 on 2021-07-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_auto_20210707_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Subject',
            new_name='subject',
        ),
    ]
