# Generated by Django 3.2.5 on 2021-07-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('staffs', '0004_rename_subject_staff_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject',
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='corecode.subject'),
            preserve_default=False,
        ),
    ]
