# Generated by Django 3.2.5 on 2021-07-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_auto_20210707_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='subjects',
            new_name='subject',
        ),
    ]
