# Generated by Django 3.2.5 on 2021-07-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0006_rename_subjects_staff_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.CharField(choices=[('FR', 'FR'), ('MATH', 'MATH')], default='MATH', max_length=10),
        ),
    ]
