# Generated by Django 3.2.5 on 2021-07-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('staffs', '0007_alter_staff_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.subject'),
        ),
    ]
