# Generated by Django 3.2.5 on 2021-07-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('staffs', '0008_alter_staff_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject_1',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='one', to='corecode.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='subject_2',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='two', to='corecode.subject'),
            preserve_default=False,
        ),
    ]
