# Generated by Django 3.2.5 on 2021-07-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('staffs', '0009_auto_20210707_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject_1',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, related_name='one', to='corecode.subject'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject_2',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, related_name='two', to='corecode.subject'),
        ),
    ]
