# Generated by Django 3.2.5 on 2021-07-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_filiere_bac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['surname', 'firstname', 'note_bac']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='other_name',
            new_name='note_bac',
        ),
    ]
