# Generated by Django 3.2.5 on 2021-07-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210707_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='filiere_bac',
            field=models.CharField(choices=[('sciencesMaths', 'sciencesMaths'), ('sciencesPhysique', 'sciencesPhysique'), ('svt', 'svt')], default='sciences maths', max_length=20),
        ),
    ]
