# Generated by Django 3.2.5 on 2021-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210707_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passport',
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='students/images/'),
        ),
    ]
